# Generated by Django 3.0.6 on 2020-05-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200512_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cover_photo',
            field=models.CharField(default='https://www.voiceofsandiego.org/wp-content/uploads/2013/08/film081513.jpg', max_length=10000),
        ),
    ]
